LancerPartsShop/Models/CategoryViewModel.cs
using LancerPartsShop.Domain.Entities;

namespace LancerPartsShop.Models
{
    public class CategoryViewModel
    {
        public Category Category { get; set; }
        public IQueryable<Category> Categories { get; set; }
        public IQueryable<Product> Products { get; set; }
        //public IQueryable<Image> Images { get; set; }
    }
}

LancerPartsShop/Areas/Admin/Controllers/CategoriesController.cs
using LancerPartsShop.Domain;
using LancerPartsShop.Domain.Entities;
using LancerPartsShop.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LancerPartsShop.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class CategoriesController : Controller
	{
		private readonly DataManager dataManager;
		private readonly IWebHostEnvironment hostEnvironment;

		private readonly string[] _extensions = new string[] { ".jpg", ".png" };

		public CategoriesController(DataManager dataManager, IWebHostEnvironment hostEnvironment)
		{
			this.dataManager = dataManager;
			this.hostEnvironment = hostEnvironment;
		}

		[HttpGet]
		public IActionResult Show()
		{ 
			return View(dataManager.Categories.GetCategories());
		}

		[HttpGet]
		public IActionResult Search(string query)
		{
			var result = from item in dataManager.Categories.GetCategories()
						 where
						 EF.Functions.Like(item.Name, $"%{query}%")
						 select item;

			return View("Show", result);
		}

		public IActionResult Edit(Guid id)
		{
			var item = id == default ? new Category() : dataManager.Categories.GetCategory(id);
			return View(item);
		}

		[HttpPost]

		public IActionResult Edit(Category model, IFormFile? titleImageFile)
		{
            if (!Extensions.IsImage(titleImageFile, _extensions))
            {
                ModelState.AddModelError("Image", "Image can be only in .jpg or .png extension");
            }

            if (!ModelState.IsValid)
			{
				return View(model);
			}

			if (titleImageFile != null)
			{
				model.TitleImagePath = titleImageFile.FileName;
				using (var fs = new FileStream(Path.Combine(hostEnvironment.WebRootPath, "images/categories/", titleImageFile.FileName), FileMode.Create))
				{
					titleImageFile.CopyTo(fs);
				}
			}
			dataManager.Categories.SaveCategory(model);
            return RedirectToAction(nameof(CategoriesController.Show), nameof(CategoriesController).CutController());
        }

        [HttpPost]
		public IActionResult Delete(Guid id)
		{
			dataManager.Categories.DeleteCategory(id);
			return RedirectToAction(nameof(CategoriesController.Show), nameof(CategoriesController).CutController());
		}
	}
}

LancerPartsShop/Areas/Admin/Controllers/ProductsController.cs
using LancerPartsShop.Areas.Admin.VeiwModels;
using LancerPartsShop.Domain;
using LancerPartsShop.Domain.Entities;
using LancerPartsShop.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.ObjectModel;

namespace LancerPartsShop.Areas.Admin.Controllers
{
	[Area("Admin")]

	public class ProductsController : Controller
    {
		private readonly DataManager dataManager;
		private readonly IWebHostEnvironment hostEnvironment;

		private readonly string[] _extensions = new string[] { ".jpg", ".png" };

        public ProductsController(DataManager dataManager, IWebHostEnvironment hostEnvironment)
		{
			this.dataManager = dataManager;
			this.hostEnvironment = hostEnvironment;
		}

		[HttpGet]
		public IActionResult Show(Guid categoryId)
		{
			ViewBag.CategoryId = categoryId;
			return View(dataManager.Products.GetProductsByCategory(categoryId));
		}

		[HttpGet]
		public IActionResult Search(Guid categoryId, string query)
		{
			var result = from item in dataManager.Products.GetProducts()
						 where
						 item.CategoryId == categoryId &&
						 EF.Functions.Like(item.Name, $"%{query}%") ||
						 EF.Functions.Like(item.PartNumber.ToString(), $"%{query}%")
						 select item;

			return View("Show", result);
		}

		public IActionResult Edit(Guid id, Guid categoryId)
		{
			var model = new EditProductViewModel();
			var item = id == default ? new Product() 
			{ CategoryId = categoryId, Category = dataManager.Categories.GetCategory(categoryId) } 
			: dataManager.Products.GetProduct(id);
			model.Product = item;
			model.Images = dataManager.Imgaes.GetImagesByProduct(id);
			return View(model);
		}

		[HttpPost]

		public IActionResult Edit(EditProductViewModel model, IFormFile? titleImageFile, ICollection<IFormFile> productImages)
		{
			var images = new List<Image>();
			foreach (var image in productImages)
			{
				if (!Extensions.IsImage(image, _extensions))
				{
					ModelState.AddModelError("Image", "Image can be only in .jpg or .png extension");
				}
			}

			if (!Extensions.IsImage(titleImageFile, _extensions))
			{
				ModelState.AddModelError("Image", "Image can be only in .jpg or .png extension");
			}

			if (!ModelState.IsValid)
			{
				return View(model);
			}

			foreach (var image in productImages)
			{
                if (image != null)
                {
                    using (var fs = new FileStream(Path.Combine(hostEnvironment.WebRootPath, "images/products/", image.FileName), FileMode.Create))
                    {
                        image.CopyTo(fs);
                    }
					var tmp = new Image(image.FileName, model.Product);
					images.Add(tmp);
					model.Product.Images.Add(tmp);
                }
            }

			if (titleImageFile != null)
			{
				model.Product.TitleImagePath = titleImageFile.FileName;
				using (var fs = new FileStream(Path.Combine(hostEnvironment.WebRootPath, "images/products/", titleImageFile.FileName), FileMode.Create))
				{
					titleImageFile.CopyTo(fs);
				}
			}

			dataManager.Products.SaveProduct(model.Product);

			foreach (var image in images)
			{ 
				dataManager.Imgaes.SaveImage(image);
			}

			return RedirectToAction(nameof(ProductsController.Show), new { categoryId = model.Product.CategoryId });
		}

		public IActionResult DeleteImage(Guid id, Guid productId)
		{ 
			dataManager.Imgaes.DeleteImage(id);
			var product = dataManager.Products.GetProduct(productId);
			return RedirectToAction(nameof(ProductsController.Edit), nameof(ProductsController).CutController(), new { product.Id, product.CategoryId });
		}

		[HttpPost]
		public IActionResult Delete(Guid id)
		{
            dataManager.Products.DeleteProduct(id);
            return RedirectToAction(nameof(CategoriesController.Show), nameof(CategoriesController).CutController());

        }
    }
}

LancerPartsShop/Controllers/CategoryController.cs
using LancerPartsShop.Domain;
using LancerPartsShop.Domain.Entities;
using LancerPartsShop.Models;
using Microsoft.AspNetCore.Mvc;

namespace LancerPartsShop.Controllers
{
    public class CategoryController : Controller
    {
        public readonly DataManager dataManager;

        public CategoryController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }
        public IActionResult Category(Guid id)
        {
            var model = new CategoryViewModel();
            model.Category = dataManager.Categories.GetCategory(id);
            model.Products = dataManager.Products.GetProductsByCategory(id);
            model.Categories = dataManager.Categories.GetCategories();
            return View(model);
        }
    }
}

LancerPartsShop/Areas/Admin/Views/Categories/Edit.cshtml
@model Category
@{
	string title = $"Editing {Model.Name}";
	ViewBag.Title = title;
}

<script src="~/js/ckeditor/ckeditor.js"></script>

<div class="container">
	<h2>@title</h2>
	<div>
		<form asp-area="Admin" asp-controller="Categories" asp-action="Edit" method="post" enctype="multipart/form-data">
			<input type="hidden" asp-for="Id" />
			<input type="hidden" asp-for="DateAdded" />
			<input type="hidden" asp-for="TitleImagePath" />

			<div asp-validation-summary="All"></div>
			<div class="div-box">
				<label asp-for="Name" class="form-label"></label>
				<input asp-for="Name" class="form-control" />
				<span asp-validation-for="Name"></span>
			</div>
			<div class="div-box">
				<label asp-for="Subtitle" class="form-label"></label>
				<input asp-for="Subtitle" class="form-control" />
				<span asp-validation-for="Subtitle"></span>
			</div>
			<div class="div-box">
				<label asp-for="Description" class="form-label"></label>
				<textarea asp-for="Description" class="form-control"></textarea>
				<span asp-validation-for="Description"></span>
			</div>
			<div class="div-box">
				<label asp-for="TitleImagePath" class="form-label"></label>
				<input type="file" name="titleImageFile" id="titleImageFile" class="form-control" />
				<div>
					<img class="img-thumbnail" src="~/images/categories/@Model.TitleImagePath"/>
				</div>
			</div>
			<div class="div-box">
				<label asp-for="MetaTitle" class="form-label"></label>
				<input asp-for="MetaTitle" class="form-control" />
				<span asp-validation-for="MetaTitle"></span>
			</div>
			<div class="div-box">
				<label asp-for="MetaDescription" class="form-label"></label>
				<input asp-for="MetaDescription" class="form-control" />
				<span asp-validation-for="MetaDescription"></span>
			</div>
			<div class="div-box">
				<label asp-for="MetaKeyords" class="form-label"></label>
				<input asp-for="MetaKeyords" class="form-control" />
				<span asp-validation-for="MetaKeyords"></span>
			</div>
			<input type="submit" value="Save" class="btn btn-outline-primary" />
		</form>
	</div>
</div>

<script>
	window.onload = function() {
		var newCKEdit = CKEDITOR.replace('@Html.IdFor(x => x.Description)');
		newCKEdit.updateElement();
	}
</script>

LancerPartsShop/Areas/Admin/Views/Categories/Show.cshtml
@model IQueryable<Category>

@{
	string pageTitle = "Categoris";
	ViewBag.Title = pageTitle;
}

<section class="admin__panel">
	<div class="container">
		<h3>Categories</h3>
		<form asp-area="Admin" asp-controller="Categories" asp-action="Search" method="get" class="d-flex">
			<input class="form-control me-2" type="search" name="query" placeholder="Поиск" aria-label="Search">
			<input class="btn btn-outline-warning" type="submit" value="Найти" />
		</form>
		<div class="div-box">
			<a asp-area="Admin" asp-controller="Categories" asp-action="Edit" asp-route-id="" class="btn btn-outline-primary">Add new</a>
		</div>
		@if (Model.Any())
		{
			<div>
				@foreach (var item in Model)
				{
					<div>
						<a asp-area="" asp-controller="Category" asp-action="Index" asp-route-id="@item.Id" class="btn btn-outline-info">
							@($"{item.Name}")
							</a>
						|
						<a asp-area="Admin" asp-controller="Products" asp-action="Show" asp-route-categoryId="@item.Id" class="btn btn-outline-info">Products</a>
						|
						<a asp-area="Admin" asp-controller="Categories" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-success">Edit</a>
						|
						<form style="display: inline-block;" id="form-@item.Id" asp-area="Admin" asp-controller="Categories" asp-action="Delete" asp-route-id="@item.Id">
						<input type="hidden" name="id" value="@item.Id" />
						<a href="#" onclick="document.getElementById('form-@item.Id').submit();" class="btn btn-outline-danger">Delete</a>
						</form>
					</div>
				}
			</div>	
		}
	</div>
</section>