LancerPartsShop/Areas/Admin/Controllers/BlogItemsController.cs
using LancerPartsShop.Domain;
using LancerPartsShop.Domain.Entities;
using LancerPartsShop.Service;
using Microsoft.AspNetCore.Mvc;

namespace LancerPartsShop.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class BlogItemsController : Controller
	{
		private readonly DataManager dataManager;
		private readonly IWebHostEnvironment hostEnvironment;
		private readonly string[] _extensions = new string[] { ".jpg", ".png" };

		public BlogItemsController(DataManager dataManager, IWebHostEnvironment hostEnvironment)
		{
			this.dataManager = dataManager;
			this.hostEnvironment = hostEnvironment;
		}

		public IActionResult Edit(Guid id)
		{
			var item = id == default ? new BlogItem() : dataManager.BlogItems.GetBlogItem(id);
			return View(item);
		}

		[HttpPost]
		public IActionResult Edit(BlogItem model, IFormFile? titleImageFile)
		{
            if (!Extensions.IsImage(titleImageFile, _extensions))
            {
                ModelState.AddModelError("Image", "Image can be only in .jpg or .png extension");
            }

            if (!ModelState.IsValid)
			{
				return View(model);
			}

			if (titleImageFile != null)
			{
				model.TitleImagePath = titleImageFile.FileName;
				using (var fs = new FileStream(Path.Combine(hostEnvironment.WebRootPath, "images/", titleImageFile.FileName), FileMode.Create))
				{
					titleImageFile.CopyTo(fs);
				}
			}
			dataManager.BlogItems.SaveBlogItem(model);
			return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
		}

		[HttpPost]
		public IActionResult Delete(Guid id)
		{
			dataManager.BlogItems.DeleteBlogItem(id);
			return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
		}
	}
}

LancerPartsShop/Areas/Admin/Controllers/CategoriesController.cs
using LancerPartsShop.Domain;
using LancerPartsShop.Domain.Entities;
using LancerPartsShop.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LancerPartsShop.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class CategoriesController : Controller
	{
		private readonly DataManager dataManager;
		private readonly IWebHostEnvironment hostEnvironment;

		private readonly string[] _extensions = new string[] { ".jpg", ".png" };

		public CategoriesController(DataManager dataManager, IWebHostEnvironment hostEnvironment)
		{
			this.dataManager = dataManager;
			this.hostEnvironment = hostEnvironment;
		}

		[HttpGet]
		public IActionResult Show()
		{ 
			return View(dataManager.Categories.GetCategories());
		}

		[HttpGet]
		public IActionResult Search(string query)
		{
			var result = from item in dataManager.Categories.GetCategories()
						 where
						 EF.Functions.Like(item.Name, $"%{query}%")
						 select item;

			return View("Show", result);
		}

		public IActionResult Edit(Guid id)
		{
			var item = id == default ? new Category() : dataManager.Categories.GetCategory(id);
			return View(item);
		}

		[HttpPost]

		public IActionResult Edit(Category model, IFormFile? titleImageFile)
		{
            if (!Extensions.IsImage(titleImageFile, _extensions))
            {
                ModelState.AddModelError("Image", "Image can be only in .jpg or .png extension");
            }

            if (!ModelState.IsValid)
			{
				return View(model);
			}

			if (titleImageFile != null)
			{
				model.TitleImagePath = titleImageFile.FileName;
				using (var fs = new FileStream(Path.Combine(hostEnvironment.WebRootPath, "images/categories/", titleImageFile.FileName), FileMode.Create))
				{
					titleImageFile.CopyTo(fs);
				}
			}
			dataManager.Categories.SaveCategory(model);
            return RedirectToAction(nameof(CategoriesController.Show), nameof(CategoriesController).CutController());
        }

        [HttpPost]
		public IActionResult Delete(Guid id)
		{
			dataManager.Categories.DeleteCategory(id);
			return RedirectToAction(nameof(CategoriesController.Show), nameof(CategoriesController).CutController());
		}
	}
}

LancerPartsShop/Areas/Admin/Controllers/HomeController.cs
using LancerPartsShop.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LancerPartsShop.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class HomeController : Controller
	{
		private readonly DataManager dataManager;

		
		public HomeController(DataManager dataManager)
		{
			this.dataManager = dataManager;
		}

		[HttpGet]
		public IActionResult Index()
		{
			return View(dataManager.BlogItems.GetBlogItems());
		}

		[HttpGet]
		public IActionResult Search(string query)
		{
			var result = from item in dataManager.BlogItems.GetBlogItems()
						 where
						 EF.Functions.Like(item.Name, $"%{query}%")
						 select item;

			return View("Index", result);
		}
	}
}

LancerPartsShop/Areas/Admin/Controllers/TextFieldsController.cs
using LancerPartsShop.Domain;
using LancerPartsShop.Domain.Entities;
using LancerPartsShop.Service;
using Microsoft.AspNetCore.Mvc;

namespace LancerPartsShop.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class TextFieldsController : Controller
	{
		private readonly DataManager dataManager;

		public TextFieldsController(DataManager dataManager)
		{ 
			this.dataManager = dataManager;
		}
		public IActionResult Edit(string codeWord)
		{
			var item = dataManager.TextFields.GetTextFieldByCodeWord(codeWord);
			return View(item);
		}

		[HttpPost]
		public IActionResult Edit(TextField model)
		{
			if (ModelState.IsValid)
			{ 
				dataManager.TextFields.SaveTextField(model);
				return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
			}
			return View(model);
		}
	}
}

LancerPartsShop/Controllers/BlogController.cs
using LancerPartsShop.Domain;
using LancerPartsShop.Models;
using Microsoft.AspNetCore.Mvc;

namespace LancerPartsShop.Controllers
{
    public class BlogController : Controller
    {
        public readonly DataManager dataManager;

        public BlogController(DataManager dataManager) 
        {
            this.dataManager = dataManager;
        }
        public IActionResult Blog()
        {
            var model = new PageViewModel();
            model.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageBlog");
            model.BlogItems = dataManager.BlogItems.GetBlogItems();
            return View(model);
        }
    }
}

LancerPartsShop/Controllers/HomeController.cs
using LancerPartsShop.Domain;
using LancerPartsShop.Models;
using Microsoft.AspNetCore.Mvc;

namespace LancerPartsShop.Controllers
{
	public class HomeController : Controller
	{
		private readonly DataManager dataManager;

		public HomeController(DataManager dataManager)
		{ 
			this.dataManager = dataManager;
		}

		public IActionResult Index()
		{
			var model = new PageViewModel();
			model.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageIndex");
			model.BlogItems = dataManager.BlogItems.GetBlogItems();
			model.Categories = dataManager.Categories.GetCategories();

            return View(model);
		}
	}
}

LancerPartsShop/Areas/Admin/Views/Home/Index.cshtml
@model IQueryable<BlogItem>
@{
	string pageTitle = "Admin panel";
	ViewBag.Title = pageTitle;
}

<section class="admin__panel">
	<div class="container">
		<h1>@pageTitle</h1>
		<div>
			<h3>Categories</h3>
			<div class="div-box">
				<a asp-area="Admin" asp-controller="Categories" asp-action="Show" asp-route-id="" class="btn btn-outline-primary">Categories</a>
			</div>
			<h3>Blog items</h3>
			<form asp-area="Admin" asp-controller="Home" asp-action="Search" method="get" class="d-flex">
				<input class="form-control me-2" type="search" name="query" placeholder="Поиск" aria-label="Search">
				<input class="btn btn-outline-warning" type="submit" value="Найти" />
			</form>
			<div class="div-box">
				<a asp-area="Admin" asp-controller="BlogItems" asp-action="Edit" asp-route-id="" class="btn btn-outline-primary">Add news</a>
			</div>
			@if (Model.Any())
			{
				<div>
					@foreach(var item in Model)
					{
						<div>
							<a asp-area="Admin" asp-controller="BlogItems" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-success">Edit</a>
							|
							<form style="display: inline-block;" id="form-@item.Id" asp-area="Admin" asp-controller="BlogItems" asp-action="Delete" asp-route-id="@item.Id">
								<input type="hidden" name="id" value="@item.Id" />
								<a href="#" onclick="document.getElementById('form-@item.Id').submit();" class="btn btn-outline-danger">Delete</a>
							</form>
							|
							<a asp-area="" asp-controller="Blog" asp-action="Index" asp-route-id="@item.Id" class="btn btn-outline-info">
								@($"{item.Name}")
							</a>
						</div>
					}
				</div>	
			}
		</div>
	</div>
	<div class="div-box container">
		<h3>Edit site pages</h3>
		<a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageIndex" class="btn btn-outline-success">Home</a>
		<a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageBlog" class="btn btn-outline-success">Blog</a>
		<a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="ContactsPage" class="btn btn-outline-success">Contacts</a>
		<a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="DeliveryInfo" class="btn btn-outline-success">Product delivery info</a>
		<a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PaymentInfo" class="btn btn-outline-success">Product payment info</a>
	</div>
	<div class="div-box container logout">
		<form asp-area="" asp-controller="Account" asp-action="Logout" method="post" class="btn btn-outline-danger">
			<input type="submit" value="Log out"/>
		</form>
	</div>
</section>