LancerPartsShop/Models/CategoryViewModel.cs
using LancerPartsShop.Domain.Entities;

namespace LancerPartsShop.Models
{
    public class CategoryViewModel
    {
        public Category Category { get; set; }
        public IQueryable<Category> Categories { get; set; }
        public IQueryable<Product> Products { get; set; }
        //public IQueryable<Image> Images { get; set; }
    }
}

LancerPartsShop/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace LancerPartsShop.Models
{
	public class LoginViewModel
	{
		[Required]
		[Display(Name = "Login")]
		public string Username { get; set; }

		[Required]
		[UIHint("password")]
		[Display(Name = "Password")]
		public string Password { get; set; }

		[Display(Name = "Remember me")]
		public bool RememberMe { get; set;}
	}
}

LancerPartsShop/Models/ProductViewModel.cs
using LancerPartsShop.Domain.Entities;

namespace LancerPartsShop.Models
{
    public class ProductViewModel
    {
        public Product Product { get; set; }
        public IQueryable<Image> Images { get; set; }
        public IQueryable<Product> Products { get; set; }
        public IQueryable<Category> Categories { get; set; }
        public TextField Delivery { get; set; }
        public TextField Payment { get; set; }
    }
}

LancerPartsShop/Areas/Admin/Controllers/CategoriesController.cs
using LancerPartsShop.Domain;
using LancerPartsShop.Domain.Entities;
using LancerPartsShop.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LancerPartsShop.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class CategoriesController : Controller
	{
		private readonly DataManager dataManager;
		private readonly IWebHostEnvironment hostEnvironment;

		private readonly string[] _extensions = new string[] { ".jpg", ".png" };

		public CategoriesController(DataManager dataManager, IWebHostEnvironment hostEnvironment)
		{
			this.dataManager = dataManager;
			this.hostEnvironment = hostEnvironment;
		}

		[HttpGet]
		public IActionResult Show()
		{ 
			return View(dataManager.Categories.GetCategories());
		}

		[HttpGet]
		public IActionResult Search(string query)
		{
			var result = from item in dataManager.Categories.GetCategories()
						 where
						 EF.Functions.Like(item.Name, $"%{query}%")
						 select item;

			return View("Show", result);
		}

		public IActionResult Edit(Guid id)
		{
			var item = id == default ? new Category() : dataManager.Categories.GetCategory(id);
			return View(item);
		}

		[HttpPost]

		public IActionResult Edit(Category model, IFormFile? titleImageFile)
		{
            if (!Extensions.IsImage(titleImageFile, _extensions))
            {
                ModelState.AddModelError("Image", "Image can be only in .jpg or .png extension");
            }

            if (!ModelState.IsValid)
			{
				return View(model);
			}

			if (titleImageFile != null)
			{
				model.TitleImagePath = titleImageFile.FileName;
				using (var fs = new FileStream(Path.Combine(hostEnvironment.WebRootPath, "images/categories/", titleImageFile.FileName), FileMode.Create))
				{
					titleImageFile.CopyTo(fs);
				}
			}
			dataManager.Categories.SaveCategory(model);
            return RedirectToAction(nameof(CategoriesController.Show), nameof(CategoriesController).CutController());
        }

        [HttpPost]
		public IActionResult Delete(Guid id)
		{
			dataManager.Categories.DeleteCategory(id);
			return RedirectToAction(nameof(CategoriesController.Show), nameof(CategoriesController).CutController());
		}
	}
}

LancerPartsShop/Areas/Admin/Controllers/ProductsController.cs
using LancerPartsShop.Areas.Admin.VeiwModels;
using LancerPartsShop.Domain;
using LancerPartsShop.Domain.Entities;
using LancerPartsShop.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.ObjectModel;

namespace LancerPartsShop.Areas.Admin.Controllers
{
	[Area("Admin")]

	public class ProductsController : Controller
    {
		private readonly DataManager dataManager;
		private readonly IWebHostEnvironment hostEnvironment;

		private readonly string[] _extensions = new string[] { ".jpg", ".png" };

        public ProductsController(DataManager dataManager, IWebHostEnvironment hostEnvironment)
		{
			this.dataManager = dataManager;
			this.hostEnvironment = hostEnvironment;
		}

		[HttpGet]
		public IActionResult Show(Guid categoryId)
		{
			ViewBag.CategoryId = categoryId;
			return View(dataManager.Products.GetProductsByCategory(categoryId));
		}

		[HttpGet]
		public IActionResult Search(Guid categoryId, string query)
		{
			var result = from item in dataManager.Products.GetProducts()
						 where
						 item.CategoryId == categoryId &&
						 EF.Functions.Like(item.Name, $"%{query}%") ||
						 EF.Functions.Like(item.PartNumber.ToString(), $"%{query}%")
						 select item;

			return View("Show", result);
		}

		public IActionResult Edit(Guid id, Guid categoryId)
		{
			var model = new EditProductViewModel();
			var item = id == default ? new Product() 
			{ CategoryId = categoryId, Category = dataManager.Categories.GetCategory(categoryId) } 
			: dataManager.Products.GetProduct(id);
			model.Product = item;
			model.Images = dataManager.Imgaes.GetImagesByProduct(id);
			return View(model);
		}

		[HttpPost]

		public IActionResult Edit(EditProductViewModel model, IFormFile? titleImageFile, ICollection<IFormFile> productImages)
		{
			var images = new List<Image>();
			foreach (var image in productImages)
			{
				if (!Extensions.IsImage(image, _extensions))
				{
					ModelState.AddModelError("Image", "Image can be only in .jpg or .png extension");
				}
			}

			if (!Extensions.IsImage(titleImageFile, _extensions))
			{
				ModelState.AddModelError("Image", "Image can be only in .jpg or .png extension");
			}

			if (!ModelState.IsValid)
			{
				return View(model);
			}

			foreach (var image in productImages)
			{
                if (image != null)
                {
                    using (var fs = new FileStream(Path.Combine(hostEnvironment.WebRootPath, "images/products/", image.FileName), FileMode.Create))
                    {
                        image.CopyTo(fs);
                    }
					var tmp = new Image(image.FileName, model.Product);
					images.Add(tmp);
					model.Product.Images.Add(tmp);
                }
            }

			if (titleImageFile != null)
			{
				model.Product.TitleImagePath = titleImageFile.FileName;
				using (var fs = new FileStream(Path.Combine(hostEnvironment.WebRootPath, "images/products/", titleImageFile.FileName), FileMode.Create))
				{
					titleImageFile.CopyTo(fs);
				}
			}

			dataManager.Products.SaveProduct(model.Product);

			foreach (var image in images)
			{ 
				dataManager.Imgaes.SaveImage(image);
			}

			return RedirectToAction(nameof(ProductsController.Show), new { categoryId = model.Product.CategoryId });
		}

		public IActionResult DeleteImage(Guid id, Guid productId)
		{ 
			dataManager.Imgaes.DeleteImage(id);
			var product = dataManager.Products.GetProduct(productId);
			return RedirectToAction(nameof(ProductsController.Edit), nameof(ProductsController).CutController(), new { product.Id, product.CategoryId });
		}

		[HttpPost]
		public IActionResult Delete(Guid id)
		{
            dataManager.Products.DeleteProduct(id);
            return RedirectToAction(nameof(CategoriesController.Show), nameof(CategoriesController).CutController());

        }
    }
}

LancerPartsShop/Controllers/BlogController.cs
using LancerPartsShop.Domain;
using LancerPartsShop.Models;
using Microsoft.AspNetCore.Mvc;

namespace LancerPartsShop.Controllers
{
    public class BlogController : Controller
    {
        public readonly DataManager dataManager;

        public BlogController(DataManager dataManager) 
        {
            this.dataManager = dataManager;
        }
        public IActionResult Blog()
        {
            var model = new PageViewModel();
            model.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageBlog");
            model.BlogItems = dataManager.BlogItems.GetBlogItems();
            return View(model);
        }
    }
}

LancerPartsShop/Controllers/CategoryController.cs
using LancerPartsShop.Domain;
using LancerPartsShop.Domain.Entities;
using LancerPartsShop.Models;
using Microsoft.AspNetCore.Mvc;

namespace LancerPartsShop.Controllers
{
    public class CategoryController : Controller
    {
        public readonly DataManager dataManager;

        public CategoryController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }
        public IActionResult Category(Guid id)
        {
            var model = new CategoryViewModel();
            model.Category = dataManager.Categories.GetCategory(id);
            model.Products = dataManager.Products.GetProductsByCategory(id);
            model.Categories = dataManager.Categories.GetCategories();
            return View(model);
        }
    }
}

LancerPartsShop/Controllers/ContactsController.cs
using LancerPartsShop.Domain;
using LancerPartsShop.Models;
using Microsoft.AspNetCore.Mvc;

namespace LancerPartsShop.Controllers
{
	public class ContactsController : Controller
	{
        private readonly DataManager dataManager;

		public ContactsController(DataManager dataManager) 
		{
			this.dataManager = dataManager;
		}

        public IActionResult Contacts()
		{ 
            return View(dataManager.TextFields.GetTextFieldByCodeWord("ContactsPage"));
		}
	}
}

LancerPartsShop/Controllers/PostController.cs
using LancerPartsShop.Domain;
using Microsoft.AspNetCore.Mvc;

namespace LancerPartsShop.Controllers
{
    public class PostController : Controller
    {
        private readonly DataManager dataManager;

        public PostController(DataManager dataManager)
        { 
            this.dataManager = dataManager;
        }

        public IActionResult Post(Guid id)
        {
            return View(dataManager.BlogItems.GetBlogItem(id));
        }
    }
}

LancerPartsShop/Controllers/ProductController.cs
using LancerPartsShop.Domain;
using LancerPartsShop.Models;
using Microsoft.AspNetCore.Mvc;

namespace LancerPartsShop.Controllers
{
	public class ProductController : Controller
	{
		private readonly DataManager dataManager;

		public ProductController(DataManager dataManager)
		{
			this.dataManager = dataManager;
		}
		public IActionResult Product(Guid id)
		{
			var model = new ProductViewModel();
			model.Product = dataManager.Products.GetProduct(id);
			model.Products = dataManager.Products.GetProductsByCategory(model.Product.CategoryId);
			model.Images = dataManager.Imgaes.GetImagesByProduct(id);
			model.Categories = dataManager.Categories.GetCategories();
			model.Delivery = dataManager.TextFields.GetTextFieldByCodeWord("DeliveryInfo");
			model.Payment = dataManager.TextFields.GetTextFieldByCodeWord("PaymentInfo");
			return View(model);
		}
	}
}

LancerPartsShop/Views/Shared/BlogCardPartial.cshtml
@model BlogItem
    <div class="card news-card p-3 bg-white">
        <img src="~/images/@Model.TitleImagePath" alt="@Model.Name">
        <div class="card-body">
            <h5 class="card-title">@Model.Name</h5>
            <p class="card-text blog-card-text">
                @Model.Subtitle
            </p>
            <a asp-area="" asp-controller="Post" asp-action="Post" asp-route-id="@Model.Id" class="btn btn-outline-secondary">See more</a>
        </div>
    </div>

LancerPartsShop/Views/Shared/BlogPage.cshtml
@*In nav class "active" avalible*@

<section class="blog">
    <div class="container">
        <h2>Блог</h2>
    </div>
    <div class="blog-container container mt-5 col-12">

        @Html.PartialAsync("BlogCardPartial")

    </div>
</section>

LancerPartsShop/Views/Shared/CategoryCardPartial.cshtml
@model Category

<a asp-area="" asp-controller="Category" asp-action="Index" asp-route-id="@Model.Id" class="category col-5">
    <span class="name col-6">@Model.Name</span>
    <img src="~/images/categories/@Model.TitleImagePath" alt="@Model.Name" class="col-2">
</a>

LancerPartsShop/Views/Shared/CategoryPage.cshtml
    <section class="cat-main">
        <div class="container ">
            <div class="top row">
                <div class="categories col-2">
                    <a class="active" href="">
                        <span>Категория</span>
                    </a>
                    <a href="">
                        <span>Категория</span>
                    </a>
                    <a href="">
                        <span>Категория</span>
                    </a>
                    <a href="">
                        <span>Категория</span>
                    </a>
                    <a href="">
                        <span>Категория</span>
                    </a>
                    <a href="">
                        <span>Категория</span>
                    </a>
                    <a href="">
                        <span>Категория</span>
                    </a>
                    <a href="">
                        <span>Категория</span>
                    </a>
                    <a href="">
                        <span>Категория</span>
                    </a>

                </div>
                <div class="right col-10">
                    <div class="container container-carousel">
                        <div id="carouselExampleControls" class="carousel slide main__page" data-bs-ride="carousel">
                            <div class="carousel-inner">
                                <div class="carousel-item active">
                                    <img src="./img/slide1.jpg" class="d-block w-100" alt="slide1">
                                    <div class="carousel-caption d-none d-md-block">
                                        <h5>First slide label</h5>
                                        <p>Some representative placeholder content for the first slide.</p>
                                        <a href="" class="btn btn-outline-warning">Lorem.</a>
                                    </div>
                                </div>
                                <div class="carousel-item">
                                    <img src="./img/slide1.jpg" class="d-block w-100" alt="slide2">
                                </div>
                                <div class="carousel-item">
                                    <img src="./img/slide1.jpg" class="d-block w-100" alt="slide3">
                                </div>
                            </div>
                            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls"
                                    data-bs-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Previous</span>
                            </button>
                            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls"
                                    data-bs-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Next</span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <section class="products">
                <div class="container">
                    <div class="product__header border-bottom">
                        <h2>Category name</h2>
                    </div>

                    <!-- PRODUCTS -->

                    <div class="d-flex product__container container mt-5 col-12">

                        @Html.PartialAsync("ProductCardPartial")


                    </div>
                </div>
            </section>

            <section class="text">
                <div class="container">

                    @Html.PartialAsync("TextPartial")

                </div>
            </section>
        </div>
    </section>

LancerPartsShop/Views/Shared/Contacts.cshtml
@model TextField
@{
    ViewBag.Title = Model.Name + " | " + Config.CompanyName;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeyords;
}
<div class="container">
    <h1>@Html.Raw(Model.Name)</h1>
    @Html.Raw(Model.Description)
</div>

LancerPartsShop/Views/Shared/CssPartial.cshtml
<link rel="stylesheet" href="~/css/main.css" asp-append-version="true" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/brands.min.css"/>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"/>
<link rel="stylesheet"
	  href="https://cdn.jsdelivr.net/npm/@@fancyapps/ui@5.0/dist/fancybox/fancybox.css" />

LancerPartsShop/Views/Shared/IndexPage.cshtml
<section class="slider">
    <div class="container container-carousel">
        <div id="carouselExampleControls" class="carousel slide main__page" data-bs-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="./img/slide1.jpg" class="d-block w-100" alt="slide1">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>First slide label</h5>
                        <p>Some representative placeholder content for the first slide.</p>
                        <a href="" class="btn btn-outline-warning">Lorem.</a>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="./img/slide1.jpg" class="d-block w-100" alt="slide2">
                </div>
                <div class="carousel-item">
                    <img src="./img/slide1.jpg" class="d-block w-100" alt="slide3">
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>
</section>

<section class="categories">
    <div class="container">
        <h3>Категории</h3>
        <div class="cat-container row">

            @Html.PartialAsync("CategoryCardPartial")

        </div>
    </div>
</section>

<section class="news">
    <div class="container">
        <h3>Последние новости</h3>
    </div>
    <div class="news-container container mt-5 col-12">

        @Html.PartialAsync("BlogCardPartial.cshtml")

    </div>
</section>

<section class="text">
    <div class="container">
        @Html.PartialAsync("TextPartial")
    </div>
</section>

LancerPartsShop/Views/Shared/Login.cshtml
@model LoginViewModel
<section class="login">
  <div class="container col-2 mt-5">
  <h1>Sign in</h1>
  <form asp-area="" asp-controller="Account" asp-action="Login" method="post" asp-route-returnUrl="@ViewBag.returnUrl">
      <div asp-validation-summary="All"></div>
      <!-- Email input -->
      <div class="form-outline mb-4">
          <input asp-for="Username" type="text" class="form-control" />
          <label asp-for="Username" class="form-label">User name</label>
      </div>

      <!-- Password input -->
      <div class="form-outline mb-4">
                <input asp-for="Password" type="password" class="form-control" />
                <label asp-for="Password" class="form-label">Password</label>
      </div>

      <!-- 2 column grid layout for inline styling -->
      <div class="row mb-4">
          <div class="col ">
              <!-- Checkbox -->
              <div class="form-check">
                        <input asp-for="RememberMe" class="form-check-input" type="checkbox" value="true" checked/>
                        <label asp-for="RememberMe" class="form-check-label"> Remember me </label>
                        <span asp-validation-for="RememberMe"></span>
              </div>
          </div>
      </div>

      <!-- Submit button -->
      <input type="submit" class="btn btn-primary btn-block mb-4" value="Sign in" />
  </form>
</div>
</section>

LancerPartsShop/Views/Shared/Post.cshtml
@model BlogItem

@{
    ViewBag.Title = Model.Name + " | " + Config.CompanyName;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeyords;
}

<section class="post">
    <div class="container">
        <img src="~/images/@Model.TitleImagePath" alt="">
        <div class="text">
            <h2>@Model.Name</h2>
            <p>
                @Html.Raw(Model.Description)
            </p>
        </div>
    </div>
</section>

LancerPartsShop/Views/Shared/Product.cshtml
@model ProductViewModel
@{
    int i = 0;
    if (string.IsNullOrEmpty(Model.Product.MetaTitle))
    {
        ViewBag.Title = Model.Product.Name;
    }
    else
    {
        ViewBag.Title = Model.Product.MetaTitle;
    }    
    ViewBag.Description = Model.Product.MetaDescription;
    ViewBag.Keywords = Model.Product.MetaKeyords;
}

<section class="card-product">

  <div class="container">
        <details>
            <summary class="btn">
                <h5 class="btn btn-outline-dark">Категорії</h5>
            </summary>
        <div class="category__list product__item">

            @foreach (var item in Model.Categories)
            {
                <a class="category__list__item product__item" asp-area="" asp-controller="Category" asp-action="Index" asp-route-id="@item.Id">@item.Name</a>
            }
           
        </div>
        </details>
    <div class="card-top">
      <div class="container container-carousel card-slider col-md-8">
        <div id="carouselExampleControls" class="carousel slide main__page" data-bs-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
                <a href="~/images/products/@Model.Product.TitleImagePath" data-fancybox="gallery">
                    <img src="~/images/products/@Model.Product.TitleImagePath" class="d-block w-100" alt="@Model.Product.Name">
                </a>
            </div>
              @if(Model.Images.Any())
              {
                  @foreach(var image in Model.Images)
                  {
                     <div class="carousel-item">
                         <a href="~/images/products/@image.Path" data-fancybox="gallery">
                             <img src="~/images/products/@image.Path" class="d-block w-100" alt="@Model.Product.Name">
                         </a>
                     </div>
                  }

                  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls"
                          data-bs-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="visually-hidden">Previous</span>
                  </button>
                  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls"
                          data-bs-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="visually-hidden">Next</span>
                  </button>
              }

          </div>

        </div>
      </div>
      <div class="side-container col-md-4">
        <div class="card-sidebar">
          <div class="title">
            <h3>@Model.Product.Name</h3>
          </div>
          <div class="number">
            <p>Original number: @Model.Product.PartNumber</p>
          </div>
          <div class="subtitle">
            <p>@Model.Product.Subtitle</p>
          </div>
          <div class="price">
            <span>Цена: </span><b>@Model.Product.Price грн.</b>
          </div>

          <div class="buy-block">
            <a href="tel: 000000000" class="btn btn-outline-warning order" type="submit">Call</a>
          </div>

        </div>
      </div>
    </div>

    <div class="card-bottom">
      <div class="card-info">

        <nav>
          <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home"
              type="button" role="tab" aria-controls="nav-home" aria-selected="true">Description</button>
            <button class="nav-link" id="nav-delivery-tab" data-bs-toggle="tab" data-bs-target="#nav-delivery"
              type="button" role="tab" aria-controls="nav-delivery" aria-selected="false">@Model.Delivery.Name</button>
            <button class="nav-link" id="nav-pay-tab" data-bs-toggle="tab" data-bs-target="#nav-pay" type="button"
              role="tab" aria-controls="nav-pay" aria-selected="false">@Model.Payment.Name</button>
          </div>
        </nav>
        <div class="tab-content" id="nav-tabContent">
          <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">@Html.Raw(Model.Product.Description)
          </div>
          <div class="tab-pane fade" id="nav-delivery" role="tabpanel" aria-labelledby="nav-delivery-tab">@Html.Raw(Model.Delivery.Description)
          </div>
          <div class="tab-pane fade" id="nav-pay" role="tabpanel" aria-labelledby="nav-pay-tab">@Html.Raw(Model.Payment.Description)</div>
        </div>

      </div>
    </div>
    
        @if (Model.Products.Any(x => x.CategoryId == Model.Product.CategoryId && x.Id != Model.Product.Id))
        {
          <div class="addict-products">
              <h3>Another products</h3>
              <div class="products-cards">
                  <ul class="list-group">
                    @foreach (var item in Model.Products.Where(x => x.CategoryId == Model.Product.CategoryId && x.Id != Model.Product.Id))
                    {
                        <a asp-area="" asp-controller="Product" asp-action="Index" asp-route-id="@item.Id" class="addict-product">
                        <li class="list-group-item">
                
                            <img src="~/images/products/@item.TitleImagePath" alt="@item.Name">
                            <span>@item.Name</span>
                            <span>@item.PartNumber</span>
                            <span>@item.Price UAH</span>
                        </li>
                        </a>
                    }
                  </ul>
              </div>
          </div>
        }

    </div>
</section>

LancerPartsShop/Views/Shared/ProductCardPartial.cshtml
@model Product

<a asp-area="" asp-controller="Product" asp-action="Index" asp-route-id="@Model.Id">
  <div class="card p-3 bg-white">
    <div class="about-product text-center mt-2">
            <img src="~/images/products/@Model.TitleImagePath" class="col-12">
      <div>
        <h4>@Model.Name</h4>
      </div>
    </div>
     <div class="stats mt-2">
        <div>
            <span>Original number: @Model.PartNumber</span>
        </div>
        </div>
    <div class="stats-subtitle mt-2">
      <div>
          <span>@Model.Subtitle</span>
      </div>
     </div>
    <div class="d-flex justify-content-between total font-weight-bold mt-4">
            <span>Price:</span><span><b>@Model.Price</b> uah</span>
        </div>
  </div>
</a>

LancerPartsShop/Views/Shared/ScriptsPartial.cshtml
<script src="~/js/jquery-3.6.3.min.js" type="text/javascript"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@@fancyapps/ui@5.0/dist/fancybox/fancybox.umd.js"></script>

<script type="text/javascript">


	Fancybox.bind('[data-fancybox="gallery"]', {
		
	});
</script>